apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdevops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdevops
  template:
    metadata:
      labels:
        app: webdevops
    spec:
      containers:
      - name: webdevops
        image: 659026651741.dkr.ecr.us-east-1.amazonaws.com/asg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webdevops
    k8s-app: webdevops
  name: webdevops
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: webdevops
